version: '3.7'
services:
  web:
    build: ./django
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    # ports:
    #   - 8000:8000
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    env_file:
      - ./django/.env.prod
    depends_on:
      - db
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgresql/.env.prod
  nginx:
    build: ./nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  postgres_data:
  static:
  media: