# Generated by Django 4.2 on 2023-04-30 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('L', 'Linux'), ('B', 'BSD'), ('M', 'Mac'), ('W', 'Windows'), ('A', 'Android'), ('I', 'IOS'), ('N', 'Any OS'), ('O', 'Other')], default='O', max_length=1)),
                ('version', models.CharField(blank=True, max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
