# Generated by Django 4.2 on 2023-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='os',
            field=models.CharField(choices=[('L', 'Linux'), ('B', 'BSD'), ('M', 'Mac'), ('W', 'Windows'), ('A', 'Android'), ('I', 'IOS'), ('N', 'Any OS'), ('O', 'Other')], default='O', max_length=1, verbose_name='ОС'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='version',
            field=models.CharField(blank=True, max_length=256, verbose_name='Версия'),
        ),
    ]
