# Generated by Django 4.2 on 2023-05-02 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_alter_software_build_options_alter_software_category_and_more'),
        ('environments', '0002_alter_environment_os_alter_environment_version'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpfiles',
            name='upload',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файлы дампа памяти'),
        ),
        migrations.AlterField(
            model_name='inputfiles',
            name='upload',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файлы входных данных'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cwe',
            field=models.IntegerField(verbose_name='Номер CWE'),
        ),
        migrations.AlterField(
            model_name='report',
            name='danger',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Опасность'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='report',
            name='environments',
            field=models.ManyToManyField(to='environments.environment', verbose_name='Среды исполнения'),
        ),
        migrations.AlterField(
            model_name='report',
            name='exploitability',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Эксплуатабельность'),
        ),
        migrations.AlterField(
            model_name='report',
            name='exploitation',
            field=models.TextField(default='Нет', verbose_name='Способ эксплуатации'),
        ),
        migrations.AlterField(
            model_name='report',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='software.software', verbose_name='ПО'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
