# Generated by Django 4.2 on 2023-04-30 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('G', 'Графическое'), ('C', 'Консольное'), ('L', 'Библиотека'), ('A', 'Приложение')], default='A', max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('version', models.CharField(default='Unknown', max_length=100)),
                ('build_options', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
